Spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-183.railway.app:7470/railway
    username: postgres
    password: krGRcar5WA8HzzxJGKjy
  jpa:
    open-in-view: false
    hibernate: 
      ddl-auto: validate